version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

  chrome-node:
    image: selenium/node-chrome:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    scale: 2

  firefox-node:
    image: selenium/node-firefox:4.15.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    scale: 2

  test-runner:
    build: .
    depends_on:
      - selenium-hub
      - chrome-node
      - firefox-node
    environment:
      - GRID_URL=http://selenium-hub:4444/wd/hub
      - ENVIRONMENT=qa
    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    command: ["python", "-m", "pytest", "--alluredir=reports/allure/allure-results", "-n", "4"]