app:
  base_url: https://staging.saucedemo.com
  environment: staging
  debug_mode: false

api:
  base_url: https://staging-api.reqres.in/api
  timeout: 30
  verify_ssl: true

test:
  parallel_count: 6
  retry_count: 2
  screenshot:
    on_success: false
  video_recording: false

logging:
  level: INFO
  file_path: logs/staging/automation-staging.log